export type OrganizationLanguage = "en" | "cn";

type TextPair = readonly [string, string];

export const ORGANIZATION_TEXT = {
  leaveTitle: ["Leave Requests", "请假申请"] as TextPair,
  leaveSubtitle: [
    "Submit and review leave, overtime, and attendance exceptions.",
    "提交并审核请假、加班与出勤异常。",
  ] as TextPair,
  newRequest: ["New Request", "新建申请"] as TextPair,
  employee: ["Employee", "员工"] as TextPair,
  department: ["Department", "部门"] as TextPair,
  date: ["Date", "日期"] as TextPair,
  type: ["Type", "类型"] as TextPair,
  time: ["Time", "时间"] as TextPair,
  start: ["Start", "开始"] as TextPair,
  end: ["End", "结束"] as TextPair,
  reason: ["Reason", "原因"] as TextPair,
  status: ["Status", "状态"] as TextPair,
  createdBy: ["Created By", "创建人"] as TextPair,
  approvedBy: ["Approved By", "审核人"] as TextPair,
  action: ["Action", "操作"] as TextPair,
  loadingRequests: ["Loading requests...", "加载申请记录..."] as TextPair,
  loadingEmployees: ["Loading employees...", "加载员工..."] as TextPair,
  noRequests: ["No leave requests found.", "暂无请假申请。"] as TextPair,
  noEmployees: ["No active employees", "没有可用员工"] as TextPair,
  approve: ["Approve", "批准"] as TextPair,
  reject: ["Reject", "拒绝"] as TextPair,
  submit: ["Submit", "提交"] as TextPair,
  cancel: ["Cancel", "取消"] as TextPair,
  close: ["Close", "关闭"] as TextPair,
  loading: ["Loading...", "加载中..."] as TextPair,
  noAttendanceRecords: [
    "No attendance records found",
    "未找到出勤记录",
  ] as TextPair,
  accountNotIdentified: [
    "Current login account could not be identified. Approval is disabled.",
    "无法识别当前登录账户，无法执行审核。",
  ] as TextPair,
  endTimeMustBeLaterThanStartTime: ["End time must be later than start time.", "结束时间必须晚于开始时间。"] as TextPair,
  leavePermission: ["Leave / Permission", "请假 / 外出"] as TextPair,
  submitReviewAndTrackEmployeeLeaveAndPermissionRequests: ["Submit, review and track employee leave and permission requests.", "提交、查看和审核员工请假与外出申请。"] as TextPair,
  newRequest2: ["New Request", "新申请"] as TextPair,
  totalRequests: ["Total Requests", "总申请数"] as TextPair,
  pending: ["Pending", "待审核"] as TextPair,
  approved: ["Approved", "已批准"] as TextPair,
  rejected: ["Rejected", "已拒绝"] as TextPair,
  noAttendance: ["No Attendance", "未打卡"] as TextPair,
  oaCompleted: ["OA Completed", "OA 已完成"] as TextPair,
  leavePermissionRequests: ["Leave & Permission Requests", "申请记录"] as TextPair,
  requestsAreLoadedFromTheLeaveApiAndStoredIn: ["Requests are loaded from the Leave API and stored in the database.", "申请记录来自 Leave API，并保存到数据库。"] as TextPair,
  records: ["records", "条记录"] as TextPair,
  allEmployees: ["All Employees", "所有员工"] as TextPair,
  allDepartments: ["All Departments", "所有部门"] as TextPair,
  allTypes: ["All Types", "所有类型"] as TextPair,
  allStatuses: ["All Statuses", "所有状态"] as TextPair,
  allOaNumbers: ["All OA Numbers", "所有 OA 编号"] as TextPair,
  hasOaNumber: ["Has OA Number", "有 OA 编号"] as TextPair,
  noOaNumber: ["No OA Number", "无 OA 编号"] as TextPair,
  oaNumber: ["OA Number", "OA 编号"] as TextPair,
  noLeaveRequestsYet: ["No leave requests yet.", "暂无申请记录"] as TextPair,
  save: ["Save", "保存"] as TextPair,
  edit: ["Edit", "编辑"] as TextPair,
  working: ["Working...", "处理中..."] as TextPair,
  managerApprovalRequired: ["Manager approval required", "等待经理权限"] as TextPair,
  waitingForManager: ["Waiting for manager", "等待直属经理"] as TextPair,
  previous: ["Previous", "上一页"] as TextPair,
  next: ["Next", "下一页"] as TextPair,
  newLeavePermissionRequest: ["New Leave / Permission Request", "新建请假 / 外出申请"] as TextPair,
  newRequestsAreCreatedWithPendingStatus: ["New requests are created with Pending status.", "提交后状态为待审核。"] as TextPair,
  employee2: ["Employee", "选择员工"] as TextPair,
  employeeNo: ["Employee No.", "员工工号"] as TextPair,
  employeeName: ["Employee Name", "员工姓名"] as TextPair,
  annualLeave: ["Annual Leave", "年假"] as TextPair,
  sickLeave: ["Sick Leave", "病假"] as TextPair,
  permission: ["Permission", "请假 / 外出"] as TextPair,
  overtime: ["Overtime", "加班"] as TextPair,
  absentWithoutLeave: ["Absent Without Leave", "旷工"] as TextPair,
  noAttendanceType: ["No Attendance Type", "未打卡类型"] as TextPair,
  select: ["Select", "请选择"] as TextPair,
  noCheckIn: ["No Check-in", "未打上班卡"] as TextPair,
  noCheckOut: ["No Check-out", "未打下班卡"] as TextPair,
  noCheckInCheckOut: ["No Check-in & Check-out", "上下班均未打卡"] as TextPair,
  startTime: ["Start Time", "开始时间"] as TextPair,
  endTime: ["End Time", "结束时间"] as TextPair,
  enterTheReasonForThisRequest: ["Enter the reason for this request...", "请输入申请原因..."] as TextPair,
  submitting: ["Submitting...", "提交中..."] as TextPair,
  submitRequest: ["Submit Request", "提交申请"] as TextPair,
  failedToLoadAttendanceData: ["Failed to load attendance data.", "加载考勤数据失败。"] as TextPair,
  attendanceSyncFailed: ["Attendance sync failed.", "考勤同步失败。"] as TextPair,
  dailyAttendance: ["Daily Attendance", "每日考勤"] as TextPair,
  viewEmployeeAttendanceResultsAndHoursByDay: ["View employee attendance results and hours by day.", "按月份查看员工每日考勤结果与工时。"] as TextPair,
  thisMonth: ["This Month", "本月"] as TextPair,
  syncing: ["Syncing...", "同步中..."] as TextPair,
  syncAttendance: ["Sync Attendance", "同步考勤"] as TextPair,
  dSNS: ["D/S / N/S", "D/S / N/S"] as TextPair,
  shift1: ["Shift 1", "班次 1"] as TextPair,
  shift4: ["Shift 4", "班次 4"] as TextPair,
  rest: ["Rest", "休息"] as TextPair,
  permission2: ["Permission", "请假/外出"] as TextPair,
  searchEmployee: ["Search Employee", "搜索员工"] as TextPair,
  nameEmployeeNo: ["Name / employee no...", "姓名 / 工号..."] as TextPair,
  allDepartments2: ["All Departments", "全部部门"] as TextPair,
  shift: ["Shift", "班次"] as TextPair,
  allShifts: ["All Shifts", "全部班次"] as TextPair,
  resetFilters: ["Reset Filters", "重置筛选"] as TextPair,
  employees: ["Employees", "员工"] as TextPair,
  plannedHours: ["Planned Hours", "计划工时"] as TextPair,
  month: ["Month", "当前月份"] as TextPair,
  source: ["Source", "数据来源"] as TextPair,
  shiftApi: ["Shift API", "班次接口"] as TextPair,
  mode: ["Mode", "状态"] as TextPair,
  syncing2: ["Syncing", "同步中"] as TextPair,
  onDemand: ["On demand", "按需同步"] as TextPair,
  readOnly: ["Read only", "只读"] as TextPair,
  totalHours: ["Total Hours", "总工时"] as TextPair,
  al: ["AL", "年假"] as TextPair,
  mc: ["MC", "病假"] as TextPair,
  upl: ["UPL", "外出"] as TextPair,
  a: ["A", "旷工"] as TextPair,
  off: ["OFF", "休息"] as TextPair,
  noAttendanceDataFound: ["No attendance data found", "没有找到考勤数据"] as TextPair,
  dailyAttendanceIsStoredInAttendanceDailyAlMcUpl: ["Daily Attendance is stored in attendance_daily. AL / MC / UPL / A immediately override the corresponding date; OT does not affect Daily Attendance; future dates remain blank.", "每日考勤数据保存于 attendance_daily；AL / MC / UPL / A 直接覆盖对应日期，OT 不影响每日考勤，未来日期保持空白。"] as TextPair,
  p: ["P", "出勤"] as TextPair,
  a2: ["A", "缺勤"] as TextPair,
  noEmployeeAttendanceData: ["No employee attendance data", "没有员工考勤数据"] as TextPair,
  failedToLoadAttendanceOverview: ["Failed to load attendance overview.", "加载考勤概览失败。"] as TextPair,
  attendanceManagement: ["Attendance Management", "考勤管理"] as TextPair,
  attendanceOverview: ["Attendance Overview", "考勤概览"] as TextPair,
  monthlyAttendanceDailyEmployeesPresentDepartmentPerformanceLeaveAndOvertime: ["Monthly attendance, daily employees present, department performance, leave and overtime overview.", "员工月度考勤、每日出勤人员、部门表现、请假与加班总览。"] as TextPair,
  previousMonth: ["Previous month", "上个月"] as TextPair,
  nextMonth: ["Next month", "下个月"] as TextPair,
  presentDays: ["Present Days", "月度出勤"] as TextPair,
  wholeMonth: ["Whole month", "整个月份"] as TextPair,
  attendanceRate: ["Attendance Rate", "出勤率"] as TextPair,
  employeeDays: ["Employee-days", "员工天数"] as TextPair,
  absent: ["Absent", "缺勤"] as TextPair,
  a3: ["A", "旷工 · A"] as TextPair,
  attendanceDaily: ["attendance_daily", "每日考勤"] as TextPair,
  al2: ["AL", "年假 · AL"] as TextPair,
  mc2: ["MC", "病假 · MC"] as TextPair,
  permission3: ["Permission", "外出"] as TextPair,
  upl2: ["UPL", "外出 · UPL"] as TextPair,
  restDays: ["Rest Days", "休息日"] as TextPair,
  off2: ["OFF", "休息 · OFF"] as TextPair,
  requests: ["requests", "申请"] as TextPair,
  monthlyAttendanceTrend: ["Monthly Attendance Trend", "月度出勤趋势"] as TextPair,
  dailyAttendanceRateAcrossTheSelectedMonth: ["Daily attendance rate across the selected month.", "按照所选月份逐日显示员工出勤率。"] as TextPair,
  monthlyAverage: ["Monthly Average", "月度平均"] as TextPair,
  monthlyStatusDistribution: ["Monthly Status Distribution", "月度状态分布"] as TextPair,
  fullMonthAttendanceDailyStatusDistribution: ["Full-month attendance_daily status distribution.", "整个月份的 每日考勤状态统计。"] as TextPair,
  present: ["Present", "出勤"] as TextPair,
  employeeMonthlyAttendance: ["Employee Monthly Attendance", "员工月度考勤"] as TextPair,
  monthlyAttendanceRateAndStatusBreakdownForEachEmployee: ["Monthly attendance rate and status breakdown for each employee.", "每位员工整个月份的出勤及状态构成。"] as TextPair,
  legend: ["Legend", "图例"] as TextPair,
  pPresent: ["P / Present", "出勤"] as TextPair,
  dailyAttendance2: ["Daily Attendance", "每日出勤"] as TextPair,
  clickAnyDateToSeeExactlyWhoWasPresent: ["Click any date to see exactly who was present.", "点击日期即可查看当天实际出勤人员。"] as TextPair,
  selectedDate: ["Selected Date", "当前日期"] as TextPair,
  employeesPresent: ["Employees Present", "当天出勤人员"] as TextPair,
  people: ["people", "人"] as TextPair,
  noPresentEmployeesRecordedForThisDay: ["No present employees recorded for this day.", "当天没有出勤记录。"] as TextPair,
  dayShift: ["☀️ Day Shift", "☀️ 白班"] as TextPair,
  noDayShiftEmployees: ["No day-shift employees", "没有白班出勤人员"] as TextPair,
  nightShift: ["🌙 Night Shift", "🌙 夜班"] as TextPair,
  noNightShiftEmployees: ["No night-shift employees", "没有夜班出勤人员"] as TextPair,
  monthlyDepartmentPerformance: ["Monthly Department Performance", "部门月度表现"] as TextPair,
  departmentAttendancePerformanceAcrossTheWholeMonth: ["Department attendance performance across the whole month.", "按照整个月份员工天数计算部门出勤率。"] as TextPair,
  rate: ["Rate", "出勤率"] as TextPair,
  overtimeSummary: ["Overtime Summary", "加班概况"] as TextPair,
  otIsTrackedSeparatelyFromDailyAttendance: ["OT is tracked separately from Daily Attendance.", "OT 独立于 每日考勤。"] as TextPair,
  requests2: ["Requests", "申请数"] as TextPair,
  thisMonth2: ["This month", "本月"] as TextPair,
  totalHours2: ["Total Hours", "总时长"] as TextPair,
  note: ["Note", "说明"] as TextPair,
  otDoesNotOverrideDailyAttendanceThisSectionSummarizesMonthly: ["OT does not override Daily Attendance. This section summarizes monthly OT requests and duration only.", "OT 不覆盖 每日考勤，仅在本区域统计 OT 申请和时长。"] as TextPair,
  recentRequests: ["Recent Requests", "最新申请"] as TextPair,
  latestLeavePermissionAndOtRequests: ["Latest leave, permission and OT requests.", "最近的请假、外出和 OT 申请。"] as TextPair,
  noRequestsYet: ["No requests yet.", "暂无申请记录"] as TextPair,
  monthlyAttendancePerformance: ["Monthly Attendance Performance", "月度考勤表现"] as TextPair,
  monthlyPerformanceBasedOnAttendanceRateAbsenceAndPlannedHours: ["Monthly performance based on attendance rate, absence and planned hours.", "从整体出勤率、缺勤控制和计划工时查看本月表现。"] as TextPair,
  presentPerformance: ["Present Performance", "出勤表现"] as TextPair,
  absenceControl: ["Absence Control", "缺勤控制"] as TextPair,
  monthlyStatus: ["Monthly Status", "月度状态"] as TextPair,
  thisPageSummarizesTheSelectedMonthFromAttendanceDailyClick: ["This page summarizes the selected month from attendance_daily. Click a date to see employees present that day. AL / MC / UPL / A follow Daily Attendance rules, while OT is tracked separately.", "本页面按所选月份统计 每日考勤；点击日期可查看当天出勤人员。AL / MC / UPL / A 按 每日考勤 规则统计，OT 独立统计。"] as TextPair,
  text4Hours: ["4 Hours", "4小时"] as TextPair,
  dayShift2: ["Day Shift", "白班"] as TextPair,
  nightShift2: ["Night Shift", "夜班"] as TextPair,
  text8Hours: ["8 Hours", "8小时"] as TextPair,
  day: ["Day", "白班"] as TextPair,
  night: ["Night", "夜班"] as TextPair,
  workSchedule: ["Work Schedule", "工作排班日历"] as TextPair,
  choose14OrOffForEachFutureDate: ["Choose 1, 4, or OFF for each future date.", "选择未来每个日期的 1、4 或休息。"] as TextPair,
  forFutureMonthsClickADateToCycle14: ["For future months, click a date to cycle 1 → 4 → OFF → clear; 1=08:00–17:00, 4=4 hours (08:00–12:00 or 12:00–17:00).", "未来月份点击日期可循环选择 1 → 4 → OFF → 清空；1=08:00–17:00，4=4小时（08:00–12:00或12:00–17:00）。"] as TextPair,
  smartLogisticSemiMonthlyShiftRotation: ["Smart Logistic semi-monthly shift rotation", "智能物流半月轮班管理"] as TextPair,
  employeesComeFromOrganizationManagementShiftAndRotationDataAre: ["Employees come from Organization Management; shift and rotation data are stored in MySQL", "员工来自组织管理；班次和轮班规则由数据库维护"] as TextPair,
  rotationMembersAlternateAccordingToDatabasePairGroup: ["Rotation members alternate according to database Pair Group", "根据数据库 Pair Group 交替轮换"] as TextPair,
  currentShiftMasterData: ["Current shift master data", "当前系统班次主数据"] as TextPair,
  smartLogisticRotationRulesStoredInMysql: ["Smart Logistic rotation rules stored in MySQL", "数据库中的 智能物流轮班规则"] as TextPair,
  onlyRotationEmployeesCanBePairedEachPairMustContain: ["Only Rotation employees can be paired; each pair must contain 1 D/S + 1 N/S. Fixed employees never rotate.", "仅 Rotation 员工可配对；每组必须 1 名 D/S + 1 名 N/S。Fixed 员工不会轮班。"] as TextPair,
  changesToDSNSAreSavedToThe: ["Changes to D/S / N/S are saved to the database", "调整 D/S / N/S 将同步保存到数据库"] as TextPair,
  scheduleLoadedFromTheDatabase: ["Schedule loaded from the database", "排班已从数据库加载"] as TextPair,
  viewSmartLogisticMonthlySchedule: ["View Smart Logistic monthly schedule", "查看 智能物流 月度排班"] as TextPair,
  searchEmployee2: ["Search employee", "搜索员工"] as TextPair,
  hours: ["Hours", "工时"] as TextPair,
  attendanceRule: ["Attendance Rule", "考勤规则"] as TextPair,
  automaticResultPriority: ["Automatic result priority", "自动考勤结果优先级"] as TextPair,
  auto: ["AUTO", "自动"] as TextPair,
  overrideResult: ["Override result", "覆盖结果"] as TextPair,
  confirmReactivateEmployee: [
    "Are you sure you want to reactivate {name}?",
    "确定要重新启用员工 {name} 吗？",
  ] as TextPair,
  failedToReactivateEmployee: [
    "Failed to reactivate employee.",
    "员工重新启用失败。",
  ] as TextPair,
  paginationSummary: [
    "Page {currentPage} of {totalPages} · {count} records",
    "第 {currentPage} / {totalPages} 页 · 共 {count} 条",
  ] as TextPair,
  mondayShort: ["Mon", "一"] as TextPair,
  tuesdayShort: ["Tue", "二"] as TextPair,
  wednesdayShort: ["Wed", "三"] as TextPair,
  thursdayShort: ["Thu", "四"] as TextPair,
  fridayShort: ["Fri", "五"] as TextPair,
  saturdayShort: ["Sat", "六"] as TextPair,
  sundayShort: ["Sun", "日"] as TextPair,
} as const;

export type OrganizationTextKey = keyof typeof ORGANIZATION_TEXT;

export function organizationText(
  key: OrganizationTextKey,
  language: OrganizationLanguage
): string {
  const pair = ORGANIZATION_TEXT[key];
  return pair[language === "cn" ? 1 : 0];
}

export function organizationLanguageValue<T>(
  language: OrganizationLanguage,
  englishValue: T,
  chineseValue: T,
): T {
  return language === "cn" ? chineseValue : englishValue;
}
