import type { SafetyLanguage } from "./types";

export const SAFETY_TEXT = {
  management: ["Safety Management", "安全管理"],
  submissionCenter: ["Safety Submission Center", "安全提交中心"],
  managementOverviewDescription: [
    "Monitor all weekly safety obligations, HSE meetings every Tuesday, and monthly requirements.",
    "监控所有每周安全要求、每周二HSE会议以及每月安全要求。",
  ],
  previousMonth: ["Previous month", "上个月"],
  nextMonth: ["Next month", "下个月"],
  month: ["Month", "月份"],
  monthlyOverview: ["MONTHLY OVERVIEW", "月度总览"],
  safetyProgress: ["Safety Progress", "安全进度"],
  progressDescription: [
    "Progress is calculated from all weekly obligations and monthly targets. HSE Tuesday is counted through the checklist.",
    "进度根据所有每周要求和每月目标计算。每周二HSE通过检查清单统计。",
  ],
  completedRequirements: ["Completed requirements", "已完成要求"],
  weeklyControlsSummary: [
    "6 weekly controls × 4 weeks + monthly targets",
    "每周6项要求 × 4周 + 每月目标",
  ],
  overallCompletion: ["Overall completion", "总体完成率"],
  weekly: ["Weekly", "每周"],
  monthly: ["Monthly", "每月"],
  hazardCase: ["Hazard Case", "安全隐患/案件"],
  weeklyControls: ["6 controls every week", "每周6项要求"],
  monthlyControls: ["Fire drill, meeting, cases, PPT & rewards", "消防演练、会议、案件、PPT及奖励"],
  hazardAttention: ["A case needs attention", "存在需要关注的案件"],
  noHazardThisMonth: ["No cases this month", "本月无案件"],
  weeklyControl: ["Weekly Control", "每周控制"],
  weeklyControlDescription: [
    "Monitor all weekly safety obligations. Click a week to open the work panel below.",
    "监控所有每周安全要求。点击某一周可打开下方工作面板。",
  ],
  progress: ["Progress", "进度"],
  weekLabel: ["Week", "周"],
  week: ["Week {week}", "第{week}周"],
  uncheck: ["Uncheck", "取消检查"],
  completed: ["Completed", "已完成"],
  pending: ["Pending", "待提交"],
  completedParticipated: ["Completed / Participated", "已完成 / 已参加"],
  notSubmitted: ["Not Submitted", "未提交"],
  weekSelected: ["Week {week} selected", "已选择第{week}周"],
  activity: ["Activity", "活动"],
  weekActivity: ["Week {week} Activity", "第{week}周活动"],
  actionDescription: [
    "Upload, Update, View, and Checklist are performed here.",
    "上传、更新、查看和检查均在此处完成。",
  ],
  completedShort: ["completed", "已完成"],
  files: ["files", "个文件"],
  file: ["file", "个文件"],
  noEvidence: ["No evidence", "无证据文件"],
  checklist: ["Checklist", "检查清单"],
  attendanceRecorded: ["Attendance recorded", "已记录参加情况"],
  noEvidenceShort: ["No evidence", "无证据"],
  view: ["View", "查看"],
  update: ["Update", "更新"],
  upload: ["Upload", "上传"],
  check: ["✓ Check", "✓ 检查"],
  evidenceLibrary: ["Evidence Library", "证据文件库"],
  evidenceDescription: ["Files already uploaded for Week {week}.", "第{week}周已上传的文件。"],
  attachments: ["attachments", "个附件"],
  noEvidenceTitle: ["No evidence yet", "暂无证据"],
  evidenceWillAppear: ["Files will appear after upload.", "上传后文件将显示在这里。"],
  weekSnapshot: ["Week Snapshot", "每周快照"],
  snapshotDescription: ["Summary of the selected week.", "当前所选周的摘要。"],
  lastUpload: ["Last Upload", "最后上传"],
  monthlyRequirements: ["Monthly Requirements", "每月要求"],
  monthlyRequirementsDescription: [
    "Monthly requirements: fire drill, monthly meeting, hazard cases, Safety PPT, and 2 rewarded findings.",
    "每月要求：消防演练、月度会议、安全隐患/案件、安全PPT以及2项奖励发现。",
  ],
  submitted: ["submitted", "已提交"],
  requirementRules: ["Requirement Rules", "要求规则"],
  requirementRulesDescription: [
    "Summary of upload rules according to the requirements you defined.",
    "根据你设定的要求汇总上传规则。",
  ],
  checklistOnly: ["Checklist only", "仅检查清单"],
  photoVideo: ["Photo + Video", "照片 + 视频"],
  beforeAfter: ["Before + After photos", "前后对比 照片"],
  videoExcel: ["Video + Excel", "视频 + Excel"],
  pptFile: ["PPT file", "PPT文件"],
  date: ["Date", "日期"],
  pic: ["PIC", "负责人"],
  location: ["Location", "地点"],
  description: ["Description", "描述"],
  descriptionEnglish: ["Description (English)", "描述（英文）"],
  descriptionChinese: ["Description (Chinese)", "描述（中文）"],
  describeActivityChinese: [
    "Describe the activity or finding in Chinese...",
    "请用中文描述活动或发现...",
  ],
  attachment: ["Attachment", "附件"],
  enterPic: ["Enter PIC", "输入负责人"],
  enterLocation: ["Enter location", "输入地点"],
  describeActivity: ["Describe the activity or finding...", "描述活动或发现..."],
  clickUpload: ["Click to upload", "点击上传"],
  canUploadMany: [
    "You can upload multiple files at once (photos, videos, Excel, PPT according to the requirement).",
    "可以一次上传多个文件（照片、视频、Excel、PPT，按要求上传）。",
  ],
  uploadBeforeAfter: ["Upload 2 photos: BEFORE + AFTER", "上传2张照片：前后对比"],
  uploadVideoExcel: ["Upload video and Excel", "上传视频和Excel"],
  uploadPpt: ["Upload PPT file", "上传PPT文件"],
  cancel: ["Cancel", "取消"],
  submit: ["Submit", "提交"],
  submitting: ["Submitting...", "提交中..."],
  setGreenNoCase: ["Set GREEN · No Case", "设为绿色 · 无案件"],
  noCaseQuestion: ["No case?", "没有案件？"],
  noCaseHelp: [
    "Leave attachment empty and submit. The system will record this month as GREEN · No Case.",
    "附件留空后提交，系统将本月记录为 GREEN · 无案件。",
  ],
  hseHelp: [
    "HSE meeting every Tuesday only needs a checklist. No file upload is required.",
    "每周二HSE会议只需进行检查，不需要上传文件。",
  ],
  submissionDate: ["Submission Date", "提交日期"],
  noAttachment: ["No attachment", "无附件"],
  attachmentsTitle: ["Attachments", "附件"],
  attachmentsPreview: [
    "Preview uploaded photos, videos and documents.",
    "预览已上传的照片、视频和文档。",
  ],
  powerpointPreviewHelp: [
    "PowerPoint preview will work automatically when the file is stored at an accessible HTTP/HTTPS URL. You can open the uploaded file now.",
    "当文件存储在可访问的 HTTP/HTTPS 地址时，PowerPoint 将自动预览。您现在可以打开已上传的文件。",
  ],
  excelPreviewHelp: [
    "Excel files are shown as document attachments. You can open the uploaded file now.",
    "Excel 文件将作为文档附件显示。您现在可以打开已上传的文件。",
  ],
  noBrowserPreview: [
    "This file type does not have an in-browser preview.",
    "此文件类型不支持浏览器内预览。",
  ],
  noPreview: ["No preview available", "暂无预览"],
  noStoredPreview: ["This submission has no stored preview files.", "此提交没有已存储的预览文件。"],
  submissionVerified: ["✓ Submission Verified", "✓ 提交已验证"],
  close: ["Close", "关闭"],
  open: ["Open", "打开"],
  image: ["Image", "图片"],
  video: ["Video", "视频"],
  pdf: ["PDF", "PDF"],
  powerpoint: ["PowerPoint", "PowerPoint"],
  excel: ["Excel", "Excel"],
  noCaseGreen: ["No Case · GREEN", "无案件 · 绿色"],
  caseFoundRed: ["CASE FOUND · RED", "发现案件 · 红色"],
  target: ["Target", "目标"],
  defaultSafetyDescription: ["Safety documentation has been submitted.", "安全资料已提交。"],
  noCaseDefault: [
    "No hazard finding or case was found this month.",
    "本月没有发现安全隐患或案件。",
  ],
  loadingDatabase: ["Loading Safety data from database...", "正在从数据库加载安全数据..."],
  weeklyLabel: ["Weekly", "每周"],
  tuesday: ["Tuesday", "星期二"],
  overview: ["Safety Overview", "安全总览"],
  overviewDescription: [
    "IM Safety Training & Weekly Safety Activity Overview",
    "IM安全培训与每周安全活动总览",
  ],
  onTrack: ["On Track", "正常进行"],
  needsAttention: ["Needs Attention", "需要关注"],
  atRisk: ["At Risk", "存在风险"],
  safetyTraining: ["Safety Training", "安全培训"],
  trainingCompleted: ["Training completed", "培训已完成"],
  hazardFinding: ["Hazard Finding", "安全隐患发现"],
  cleaningFinding: ["Cleaning Finding", "清洁问题发现"],
  totalFindings: ["Total Findings", "发现总数"],
  currentMonth: ["Current month", "当前月份"],
  thisMonth: ["This month", "本月"],
  safetyMeeting: ["Safety Meeting", "安全会议"],
  completionRate: ["Completion Rate", "完成率"],
  overall: ["Overall", "总体"],
  safetyCompletionTrend: ["Safety Completion Trend", "安全完成趋势"],
  weeklyCompletionPerformance: ["Weekly completion performance", "每周完成情况"],
  findingStatus: ["Finding Status", "问题状态"],
  currentSafetyCaseStatus: ["Current safety case status", "当前安全案件状态"],
  closed: ["Closed", "已关闭"],
  inProgress: ["In Progress", "处理中"],
  findingOpen: ["Open", "未关闭"],
  closureRate: ["Closure Rate", "关闭率"],
  weeklyFindingTrend: ["Weekly Finding Trend", "每周问题趋势"],
  hazardAndCleaningFindings: ["Hazard and cleaning findings", "安全隐患与清洁问题发现"],
  hazard: ["Hazard", "安全隐患"],
  cleaning: ["Cleaning", "清洁"],
  weeklyRequirementCompletion: ["Weekly Requirement Completion", "每周要求完成情况"],
  completedRequirementsByWeek: ["Completed requirements by week", "按周统计已完成要求"],
  safetyTrainingPerformance: ["Safety Training Performance", "安全培训表现"],
  trainingCompletionByWeek: ["Training completion by week", "按周统计培训完成情况"],
  trainingCompletion: ["Training Completion", "培训完成情况"],
  monthlySafetyActivity: ["Monthly Safety Activity", "每月安全活动"],
  monthlyRequirementCompletion: ["Monthly requirement completion", "每月要求完成情况"],
  safetyPerformanceScore: ["Safety Performance Score", "安全绩效评分"],
  overallMonthlySafetyPerformance: ["Overall monthly safety performance", "每月整体安全绩效"],
  overviewOverallCompletion: ["Overall Completion", "总体完成率"],
  findingClosure: ["Finding Closure", "问题关闭率"],
  training: ["Training", "培训"],
  safetyScore: ["Safety Score", "安全评分"],
  weeklySafetyRequirement: ["Weekly Safety Requirement", "每周安全要求"],
  currentWeeklySafetyActivities: ["Current weekly safety activities", "当前每周安全活动"],
  weeklyCompletion: ["Weekly Completion", "每周完成情况"],
  noTrainingData: ["No training data", "暂无培训数据"],
  overviewWeek: ["Week", "周次"],
  status: ["Status", "状态"],
  trainingAttendance: ["Training Attendance", "培训出席情况"],
  actionRequired: ["Action Required", "需要处理"],
  activitiesNeedAttention: ["Activities that need attention", "需要关注和处理的安全活动"],
  noActionRequired: ["✓ No action required", "✓ 无需处理"],
  allActivitiesOnTrack: ["All safety activities are on track.", "所有安全活动均正常进行。"],
  safetyCaseNeedsAttention: ["Safety case requires attention.", "安全案件需要关注。"],
  activityNotSubmitted: ["Safety activity has not been submitted.", "安全活动尚未提交。"],
  total: ["Total", "总计"],
  safetyActivity: ["Safety Activity", "安全活动"],
  itSafetyManagementSystem: ["IM Safety Management System", "IM安全管理系统"],
  fireDrill: ["Fire Drill", "消防演练"],
  monthlyMeeting: ["Monthly Meeting", "月度会议"],
  safetyCase: ["Safety Case", "安全案件"],
  safetyPpt: ["Safety PPT", "安全PPT"],
  rewardFinding: ["Reward Finding", "奖励发现"],
  hseTuesday: ["HSE Tuesday", "HSE星期二"],
  ert: ["ERT", "ERT"],
  fiveSCleaning: ["5S / Cleaning", "5S / 清洁"],
  bbs: ["BBS", "BBS"],
} as const;

export type SafetyTextKey = keyof typeof SAFETY_TEXT;

export function safetyText(key: SafetyTextKey, language: SafetyLanguage): string {
  const pair = SAFETY_TEXT[key];
  return pair[language === "cn" ? 1 : 0];
}

export function formatSafetyText(value: string, replacements: Record<string, string>): string {
  return Object.entries(replacements).reduce(
    (result, [key, replacement]) => result.replace(`{${key}}`, replacement),
    value
  );
}

export function getLocalizedValue(
  en?: string | null,
  cn?: string | null,
  language: SafetyLanguage = "en"
): string {
  if (language === "cn") {
    return cn?.trim() || en?.trim() || "—";
  }

  return en?.trim() || cn?.trim() || "—";
}
